// app/layout.tsx
import { Ubuntu } from "next/font/google";

import "./globals.css";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";

import UserData from "@/app/_components/UserData";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: "700" });

// Define the metadata object with explicit types
export const metadata: { title: string; description: string } = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define props type for the RootLayout component
interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  
  return (
    <html lang="en">
      <body className={ubuntu.className}>
       
          <Header />
          <UserData/>
          {children}
          <Footer />

      </body>
    </html>
  );
}






